[0m15:09:28.929451 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118929fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118f3e5d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118f3e1b0>]}


============================== 15:09:28.934266 | cb8617a8-541b-45e7-9523-0d218d56bd1d ==============================
[0m15:09:28.934266 [info ] [MainThread]: Running with dbt=1.9.1
[0m15:09:28.934765 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': '/Users/mirnawong/Documents/dbt-jsonschema/tests/1.6/invalid/logs', 'debug': 'False', 'profiles_dir': '/Users/mirnawong/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt ', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:09:29.032508 [error] [MainThread]: Encountered an error:
Runtime Error
  at path []: Additional properties are not allowed ('semantic_models' was unexpected)

Error encountered in /Users/mirnawong/Documents/dbt-jsonschema/tests/1.6/invalid/dbt_project.yml
[0m15:09:29.033807 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.1857012, "process_in_blocks": "0", "process_kernel_time": 0.149864, "process_mem_max_rss": "90734592", "process_out_blocks": "0", "process_user_time": 0.901679}
[0m15:09:29.034147 [debug] [MainThread]: Command `cli deps` failed at 15:09:29.034073 after 0.19 seconds
[0m15:09:29.034407 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11894b380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118f3e300>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118f3fef0>]}
[0m15:09:29.034617 [debug] [MainThread]: Flushing usage events
[0m15:09:29.757359 [debug] [MainThread]: An error was encountered while trying to flush usage events
