[0m15:09:29.009392 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104828650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104dd3800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10503a1e0>]}


============================== 15:09:29.013166 | d270ecb3-ce47-4995-9d9c-316eb58659e1 ==============================
[0m15:09:29.013166 [info ] [MainThread]: Running with dbt=1.9.1
[0m15:09:29.013748 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mirnawong/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': '/Users/mirnawong/Documents/dbt-jsonschema/tests/1.7/invalid/logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt ', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:09:29.068648 [error] [MainThread]: Encountered an error:
Runtime Error
  at path []: Additional properties are not allowed ('semantic_models' was unexpected)

Error encountered in /Users/mirnawong/Documents/dbt-jsonschema/tests/1.7/invalid/dbt_project.yml
[0m15:09:29.069522 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.123896874, "process_in_blocks": "0", "process_kernel_time": 0.140862, "process_mem_max_rss": "91832320", "process_out_blocks": "0", "process_user_time": 0.872433}
[0m15:09:29.069723 [debug] [MainThread]: Command `cli deps` failed at 15:09:29.069682 after 0.12 seconds
[0m15:09:29.069880 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1008aeb40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10404e570>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104ff46b0>]}
[0m15:09:29.070042 [debug] [MainThread]: Flushing usage events
[0m15:09:29.754444 [debug] [MainThread]: An error was encountered while trying to flush usage events
